### ISSUE TITLE
Error during push component

### ISSUE THREAD

**Issue by aureamunoz** [halkyonio/operator#176] opened 2019-10-24 08:33 UTC
Component created with following command:
```
 hal component create client-sb -s true
? Runtime spring-boot
? Version 2.1.6.RELEASE
? Expose microservice No
? Group Id dev.snowdrop
? Artifact Id myproject
? Version 1.0.0-SNAPSHOT
? Package name dev.snowdrop.myproject
? Env variable in the 'name=value' format, simply press enter when finished 
❯ Selected Name: client-sb
 ✓  Successfully created 'client-sb' component
```
When I try to push to the cluster:
```
hal component push -c client-sb
Local changes detected for 'client-sb' component: about to push source code to remote cluster
 ✗  Waiting for component client-sb to be ready…
 ✗  error running push: error waiting for component: 'client-sb' component's status is Failed: failed to create or update Component 'client-sb': Deployment.apps "client-sb" is invalid: [spec.template.spec.volumes[1].persistentVolumeClaim.claimName: Required value, spec.template.spec.volumes[1].name: Required value, spec.template.spec.containers[0].ports[0].containerPort: Required value, spec.template.spec.containers[0].volumeMounts[1].name: Required value, spec.template.spec.containers[0].volumeMounts[1].name: Not found: "", spec.template.spec.containers[0].volumeMounts[2].name: Required value, spec.template.spec.containers[0].volumeMounts[2].name: Not found: "", spec.template.spec.containers[0].volumeMounts[3].name: Required value, spec.template.spec.containers[0].volumeMounts[3].name: Not found: ""]
```
Logs from the operator:
```
2019-10-24T10:33:09.732+0200	ERROR	kubebuilder.controller	Reconciler error	{"controller": "component-controller", "request": "demo/client-sb", "error": "failed to create or update Component 'client-sb': Service \"client-sb\" is invalid: [spec.ports[0].port: Invalid value: 0: must be between 1 and 65535, inclusive, spec.ports[0].targetPort: Invalid value: 0: must be between 1 and 65535, inclusive]"}
github.com/go-logr/zapr.(*zapLogger).Error
```

**Comment by metacosm** [comment] 2019-10-24 13:58
Duplicate of https://github.com/halkyonio/hal/issues/59

**Closed by metacosm** 2019-10-24 13:58 UTC
